dist: trusty
sudo: required
language: python
python:
  - "3.4_with_system_site_packages"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gir1.2-gtk-3.0 gir1.2-appindicator3-0.1 gir1.2-notify-0.7 python3-gi
  - sudo apt-get install -y gettext
install:
  - pip3 install -r requirements.test.txt
  - pip3 install flake8
  - pip install coveralls
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - flake8
  - pytest --cov=src/tomatinho
  - sudo make install
after_success:
  coveralls
