sudo: false
language: python
python: "3.5"
addons:
  apt:
    packages:
      - python-gi
install:
  - pip install -r requirements.test.txt
  - pip install flake8
before_script: flake8
script: pytest
