#!/usr/bin/python3

import gi

gi.require_version('Gtk', '3.0')
gi.require_version('AppIndicator3', '0.1')
gi.require_version('Notify', '0.7')

from tomatinho import tomatinho

if __name__ == '__main__':
    tomatinho.main()
